name: workflow

on:
  push:
    branches:
      alejandroz

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -name: saludar
      run: echo "hola"
      -name: despedir
      run: echo "adios"

